### ISSUE TITLE
GIEV SHRUG BACK!

### ISSUE THREAD

**Issue by Padrio** [SubliminalHQ/shiro#38]
### Description
> YOU REMOVED THE SHRUG-COMMAND

### Current behavior
> THERE IS NO SHRUG ANYMORE

### Expected behavior
> WHEN WRITING %shrug SHIRO SHOULD RESPOND WITH " ¯\\\_(ツ)\_/¯"

### What is the motivation / use case for changing the behavior?
> MAKE SHIRO GREAT AGAIN

**Comment by sn0w** [comment]
![](https://media.giphy.com/media/Zo9ACzmJgoqRy/giphy.gif)
